### ISSUE TITLE
Connect - Social network icons

### ISSUE THREAD

**Issue by dylanberry** [TorontoMobileDevelopers/MeetupApp#10]
Add social network icons on the connect screen (icon font is preferable if available):

1. Meetup
2. GitHub
3. YouTube
4. Twitter
5. WhatsApp
6. Facebook

**Comment by pbojanczyk** [comment]
implemented in commit (8d4d8a27b8501dd539f41eb0be44bc5106093cba)
I accidentally cloned the master instead of my forked repo.   (fail)

**Comment by pbojanczyk** [comment]
Also, I only tested it on Android emu

**Comment by DanielCauser** [comment]
Hey @pbojanczyk just make sure the icons are added to the iOS project with the Build action set to BundleResource!

**Comment by DanielCauser** [comment]
Oh, you used the icons from Font Awesome, NVM my comment above =P
