### ISSUE TITLE
Title is cropped on small android screens

### ISSUE THREAD

**Issue by DanielCauser** [TorontoMobileDevelopers/MeetupApp#24]
VS 1.0 (1) - Beta

![whatsapp image 2018-08-15 at 12 41 21 pm](https://user-images.githubusercontent.com/7211075/44160677-1ea69f00-a089-11e8-8398-032eeb1aa6ec.jpeg)

**Comment by ChaseFlorell** [comment]
Upgrade to the preview of forms, and then use the new title View.

**Comment by dylanberry** [comment]
We're using XF3.2 so this should be low hanging fruit. I'm going to take a look right now!

**Comment by dylanberry** [comment]
Fixed in #25
